name: Deploy Project to AWS EC2

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  Deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - name: Load and cache dependencies
        uses: ./.github/actions/cached-dev-deps
        id: cache-deps
        with:
          caching: "true"

      - name: Output cache dependencies result
        run: echo "Cache used ? ${{steps.cache-deps.outputs.used-cache}}"

      - name: Upload environment variables
        run: |
          touch .env
          echo "${{ secrets.ENV_VARIABLES }}" > .env

      - name: Restart pm2
        run: pm2 restart all

      - name: List contents
        run: ls
